name: hello
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types: [ labeled ]
jobs:
  this-is-the-job-name:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
